[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://push-your-luck-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
